name: "Configure App"
# Configure App sets up the app with the correct name and version.
#
# See: https://www.appfair.net
on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'App Version'
        required: true
        default: '0.0.1'
      build_ios:
        type: boolean
        description: 'Build iOS App'
        required: true
        default: true
      build_macos:
        type: boolean
        description: 'Build macOS App'
        required: true
        default: true

jobs:
  call-workflow:
    uses: appfair/fairground/.github/workflows/configure_app.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      build_ios: ${{ github.event.inputs.build_ios == 'true' }}
      build_macos: ${{ github.event.inputs.build_macos == 'true' }}

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

